version: "3.9"

services:
  pulsar:
    image: apachepulsar/pulsar:3.2.4
    command: >
      bin/pulsar standalone
    ports:
      - "6650:6650"
      - "8080:8080"

  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: moments
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
